CREATE TABLE address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL,
    address_name VARCHAR(100) NOT NULL,
    number VARCHAR(20) NOT NULL,
    CONSTRAINT uc_address_unique UNIQUE (city, type, address_name, number)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    age INT,
    gender VARCHAR(10),
    address_id BIGINT not null,
    is_deceased BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_user_address FOREIGN KEY (address_id) REFERENCES address(id)
);

CREATE TABLE pet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    age INT,
    type VARCHAR(20),
    is_deceased BOOLEAN DEFAULT FALSE,
    address_id BIGINT NOT NULL,
    CONSTRAINT fk_pet_address FOREIGN KEY (address_id) REFERENCES address(id)
);

CREATE TABLE user_pet_ownership (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    pet_id BIGINT NOT NULL,
    CONSTRAINT fk_ownership_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_ownership_pet FOREIGN KEY (pet_id) REFERENCES pet(id),
    CONSTRAINT uc_ownership UNIQUE (user_id, pet_id)
);
