# .github/workflows/build.yml
name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write  # needed for PR decoration/comments

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for accurate analysis

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'   # LTS build of OpenJDK
          java-version: '21'
          cache: 'maven'            # Built-in Maven cache

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}  # enables PR decoration
          # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # uncomment if using a self-hosted SonarQube server
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=tanuc-dev_bnp-user-pet-manager
      - name: Run OWASP via Maven
        run: mvn org.owasp:dependency-check-maven:check -DnvdApiKey=${{ secrets.NVD_API_KEY }}
